### ISSUE TITLE
Grammar+syntax of the definition file

### ISSUE THREAD

**Issue by ofpiyush** [daakia/daakia#4]
Current idea.

```
service AppBackend:
	server Ping()
  	server Connect(Credential) Identity
   	server Publish(Message) Ack
	server Disconnect(Disc)
	client PublishMsgs(Message) Ack
```

**Comment by ofpiyush** [comment]
I am using toml to build the AST till we have an idea of what the language should look like.

```toml
namespace = "daakia"
[[services]]
    name = "TwoWayPublish"
    [[services.server]]
        name = "Publish"
        in = true
    [[services.server]]
        name = "PubAck"
        in = true
    [[services.client]]
        name = "Publish"
        in = true
    [[services.client]]
        name = "PubAck"
        in = true

[[services]]
    name = "Echo"
    [[services.server]]
        name = "yolo"
```
